# Directories containing ffmpeg and opencv
INCLUDE_DIRS := /usr/local/include
LIBRARY_DIRS := /usr/local/lib

# Comment if you're using OpenCV 2.4
OPENCV_VERSION := 3

BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Uncomment for debugging.
# DEBUG := 1

# enable pretty build (comment to see full commands)
Q ?= @
